#!/bin/sh

set -e

STATE="$1"
FILES="$2"

PREV_JOBS="${FILES}/tmp/cron/"
NEW_USERS="${FILES}/tmp/users"



case "$STATE" in
	NeedsArtifactReboot )
		echo "No"
	;;

	SupportsRollback )
		echo "Yes"
	;;

	ArtifactInstall )
		cd ${FILES}/files
		rm -rf ${PREV_JOBS} ${NEW_USERS}
		for user in ${FILES}/files/*	; do
			[[ -d /home/${user} ]] || (useradd --create-home ${user}; echo ${user} >> ${NEW_USERS})
			CRON_FILE="/var/spool/cron/${user}"
			CRON_FILE_BACKUP="${PREV_JOBS}${user}"
			[[ -e ${CRON_FILE} ]] && cp ${CRON_FILE} ${CRON_FILE_BACKUP}
			mv ${user} ${CRON_FILE}
		done
		systemct restart crond.service
	;;

	ArtifactRollback )
		while IFS=read -l u; do
			rm "/var/spool/cron/${u}"
		done < "${FILES}/tmp/users"
		cd ${PREV_JOBS}
		for user in * ; do
			mv ${user} /var/spool/cron/${user}
		done
		systemct restart crond.service
	;;

esac
